### ISSUE TITLE
Proposition de modification de l'acceuil

### ISSUE THREAD

**Issue by SL-prog** [Sivigik/Sivigik#1]
![newversivigik](https://cloud.githubusercontent.com/assets/6438281/4853693/6c22866c-6088-11e4-817e-1310243a4857.png)

http://www.heberger-image.fr/data/images/25273_newversivigik.png

**Comment by SL-prog** [comment]
Une barre bleue est présente tout en haut de la page et suit le scrolling. Sur cette barre bleue horizontale est présent dans l'ordre : Le logo du site, une barre de recherche afin d'en effectuer sur le site (à ajouter en dernier lieu), un bouton afin d'avoir accès à la bulle d'option facebook et de même pour twitter, et enfin une zone 'Login', 'Nomdelapersonne' pour se connecter ou avoir accès à la bulle pour gérer son profil.

**Comment by Klafyvel** [comment]
question : on positionne où les événements mis en avant (post de bienvenue par exemple)
